version: '3.9'
name: fire_incidents

services:
  postgres_db: 
    image: postgres:16.0
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  dbt:
    image: dbt-dummy
    build: .
    volumes:
      - ./:/usr/src/dbt
    depends_on:
      postgres_db:
        condition: service_healthy

